L10n
rffontenelle/free-python-games pull request #1
Opened 2021-08-25 00:09 UTC by analaura09

2021-08-26 11:31 UTC, adorilson requested changes

2021-08-26 11:31 UTC, adorilson commented on docs/Makefile
> +	$(SPHINXINTL) update -p "$(BUILDDIR)/gettext" -l pt_BR
Aqui deve ficar sem os parâmetros mesmo. E aí sempre vai gerar tudo. Lembrar que esse procedimento não é apenas para pt_BR.

Em contrapartida, faltou colocar instruções (acho que no README mesmo) de que o <lang> deve ser criado em locale/ e depois disso executar o make update-po.

2021-09-01 17:03 UTC, analaura09 commented on docs/Makefile
> +	$(SPHINXINTL) update -p "$(BUILDDIR)/gettext" -l pt_BR
ok, mas o README que tem aqui é o do site, não é um próprio para o processo de I18N.

2021-09-01 23:42 UTC, adorilson commented on docs/Makefile
> +	$(SPHINXINTL) update -p "$(BUILDDIR)/gettext" -l pt_BR
Realmente. Olhando melhor vi que fica mais adequado no docs/development.rst.  Acrescenta uma seção Translate no fim do arquivo.

2021-10-07 01:04 UTC, analaura09 commented
adding the .mo and .pot files to git ignore and update docs/makefile

2021-10-07 17:28 UTC, analaura09 commented
@rffontenelle, the pull request has been updated.

2021-10-08 23:30 UTC, merged